from enum import Enum

class Animal(Enum):
    cat = "cat"
    dog = "dog"
    panda = "panda"
    koala = "koala"
    fox = "fox"
    bird = "bird"
    racoon = "racoon"
    kangaroo = "kangaroo"
    elephant = "elephant"
    giraffe = "giraffe"
    whale = "whale"
    birb = "birb"
    raccoon = "raccoon"

class Gif(Enum):
    wink = "wink"
    pat = "pat"
    hug = "hug"
    facepalm = "face-palm"

class Filter(Enum):
    greyscale = "greyscale"
    invert = "invert"
    invertgreyscale = "invertgreyscale"
    brightness = "brightness"
    threshold = "threshold"
    sepia = "sepia"
    red = "red"
    green = "green"
    blue = "blue"
    blurple = "blurple"
    pixelate = "pixelate"
    blur = "blur"
    gay = "gay"
    glass = "glass"
    wasted = "wasted"
    triggered = "triggered"
    spin = "spin"
